"""
Statement models for the extraction pipeline.

RawTriple: Output of Stage 1 (Splitting)
PipelineStatement: Output of Stage 2 (Extraction) with refined entities
"""

from typing import Optional

from pydantic import BaseModel, Field

from .entity import ExtractedEntity


class RawTriple(BaseModel):
    """
    A raw triple from Stage 1 (Splitting).

    Contains the basic text components before entity refinement.
    Generated by T5-Gemma or other splitting plugins.
    """
    subject_text: str = Field(..., description="Raw subject text")
    predicate_text: str = Field(..., description="Raw predicate text")
    object_text: str = Field(..., description="Raw object text")
    source_sentence: str = Field(..., description="The source sentence this triple was extracted from")
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Extraction confidence from the splitter"
    )

    def __str__(self) -> str:
        return f"{self.subject_text} --[{self.predicate_text}]--> {self.object_text}"

    def as_tuple(self) -> tuple[str, str, str]:
        """Return as a simple (subject, predicate, object) tuple."""
        return (self.subject_text, self.predicate_text, self.object_text)


class PipelineStatement(BaseModel):
    """
    A statement with extracted entities from Stage 2 (Extraction).

    Contains refined subject/object entities with types, spans, and confidence.
    This is the main statement type that flows through stages 2-5.
    """
    subject: ExtractedEntity = Field(..., description="The subject entity")
    predicate: str = Field(..., description="The relationship/predicate text")
    object: ExtractedEntity = Field(..., description="The object entity")
    source_text: str = Field(..., description="The source text this statement was extracted from")
    confidence_score: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Overall confidence score for this statement"
    )
    extraction_method: Optional[str] = Field(
        None,
        description="Method used to extract this statement (e.g., 'hybrid', 'gliner', 'model')"
    )

    def __str__(self) -> str:
        return f"{self.subject.text} --[{self.predicate}]--> {self.object.text}"

    def as_triple(self) -> tuple[str, str, str]:
        """Return as a simple (subject, predicate, object) tuple."""
        return (self.subject.text, self.predicate, self.object.text)

    class Config:
        frozen = False  # Allow modification during pipeline stages
